/*
 * airframes.js: every airframe id the statistics count as itself.
 *
 * Generated by scripts/airframes.js from the simulator's configs/airframes.js
 * (AIRFRAME_IDS); run it after re-pinning vendor/fdfpv, or against a checkout
 * of the simulator. It only adds: an id the simulator has retired stays, since
 * older builds still send it and its counted rows are history. `5inch` and
 * `whoop65` predate the catalogue; older clients folded every aircraft onto
 * those two. Any id not here is counted as `other`.
 *
 * This file is part of the Paraguayan Drone Combat Simulator.
 *
 * The Paraguayan Drone Combat Simulator is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or (at
 * your option) any later version.
 *
 * The Paraguayan Drone Combat Simulator is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY, without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with the Paraguayan Drone Combat Simulator. If not, see <https://www.gnu.org/licenses/>.
 */
export const AIRFRAME_IDS = [
  '5inch', 'whoop65', '7inch', '10inch', 'interceptor', 'sky1800', 'cub1400', 'radian2000',
  'bramor2300', 'slowstick1180', 'timber1500', 'timber1500f', 'cub1400f', 'bombshell1118', 'kadet1981', 'uglystik1567',
  'tigermoth1803', 'p51d1450', 'f16878', 'zagi1219', 'nrj1490', 'striker2500', 'quickie1293', 'edge1524',
  'extra1308', 'pitts850', 'wot41334',
];
